---
name: Publishing to Azure DevOps Marketplace (Dev)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install tfx-cli
        run: npm install -g tfx-cli

      - name: Run init-ado-extension.ps1
        shell: pwsh
        run: |
          ./init-ado-extension.ps1

      - name: Run build-dev.ps1
        shell: pwsh
        run: |
          ./build-dev.ps1

      - name: Package extension
        run: |
          tfx extension create --manifest-globs vss-extension-dev.json --output-path ./dist
            
      - name: Publish extension to marketplace
        run: |
          tfx extension publish --manifest-globs vss-extension-dev.json --token ${{ secrets.AZURE_DEVOPS_PAT }} --share-with experimentation
            
      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ado-extension-dev
          path: ./dist/*.vsix