---
# File with LF line endings
name: Publishing to Azure DevOps Marketplace (Dev)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install tfx-cli
        run: npm install -g tfx-cli

      # Login to Azure using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      # Get Azure DevOps access token using Azure CLI
      - name: Get Azure DevOps token
        id: get-ado-token
        run: |
          TOKEN=$(az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query accessToken -o tsv)
          echo "ADO_TOKEN=$TOKEN" >> "$GITHUB_ENV"

      - name: Run setup-dev scripts
        shell: pwsh
        run: |
          ./scripts/setup-dev.ps1

      - name: Package & Publish extension to marketplace
        run: |
          tfx extension create --manifest-globs vss-extension-dev.json --output-path ./dist
          tfx extension publish --manifest-globs vss-extension-dev.json --auth-type pat -t "${{ env.ADO_TOKEN }}" --share-with experimentation

      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ado-extension-dev
          path: ./dist/*.vsix
